# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "adhan-clock"
version = "4.2.1"
edition = "2024"
build = "build.rs"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "adhan-clock"
path = "src/main.rs"

[dependencies]
chrono = "0.4.44"
reqwest = {version = "0.10", default-features = false, features = ["rustls-tls", "blocking"]}
serde_json = "1.0.149"
slint = {version = "1.17.1", features = ["backend-android-activity-06"]}
rodio = {version = "0.22.2", default-features = false, features = ["vorbis", "playback", "tracing"]}
phf = { version = "0.14.0", features = ["macros"] }
backtrace = "0.3.76"
glob = "0.3.4"

[patch.crates-io]
i-slint-backend-android-activity = { path = "./i-slint-backend-android-activity" }

[build-dependencies]
slint-build = "1.17.1"

[package.metadata.android]
package = "io.github.Seyeleek.adhan_clock"
build_targets = ["aarch64-linux-android"]
resources = "resources/"

[package.metadata.android.sdk]
min_sdk_version = 28
target_sdk_version = 35
max_sdk_version = 35

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.uses_permission]]
name = "android.permission.ACCESS_NETWORK_STATE"

[[package.metadata.android.uses_permission]]
name = "android.permission.WAKE_LOCK"

[package.metadata.android.application]
label = "Adhan Clock"
icon = "@drawable/icon"

[package.metadata.android.application.activity]
config_changes = "orientation|keyboardHidden|screenSize|keyboard"
