// SPDX-License-Identifier: GPL-3.0-only

import { StandardListView } from "listview.slint";
import { LineEdit } from "lineedit.slint";

export component Picker inherits Rectangle {
    in-out property<bool> expanded: false;
    in property<int> current: 0;
    in property<color> text-color;
    in property<[StandardListViewItem]> entries;
    in property<length> full-height;
    in property<length> full-width;
    in property<length> font-size;
    in property<color> background-color;
    in property<length> picker-border-radius;
    in property<length> picker-drop-shadow-blur;
    in property<color> picker-drop-shadow-color;
    in property<length> picker-x;
    in property<bool> show-search: true;

    callback picked(string);
    callback searched <=> search-box.edited;

    public function update-current(current-item: int) {
        list.current-item = current-item;
    }

    public function bring-into-view(item: int) {
        list.bring-into-view(item);
    }

    changed expanded => {
        if show-search {
            if expanded {search-box.focus();}
            if !expanded {search-box.clear-focus();}
        }
    }

    Text {
        text: entries[list.current-item].text;
        color: text-color;
        font-size: parent.font-size;
        
        TouchArea {
            clicked => {
                expanded = true;
                list.bring-into-view(list.current-item);
            }
        }
    }
    Rectangle {
        visible: expanded;
        z: 4;
        height: full-height;
        width: full-width;
        y: 0;
        x: picker-x;
        background: background-color;
        border-radius: root.picker-border-radius;
        drop-shadow-color: root.picker-drop-shadow-color;
        drop-shadow-blur: root.picker-drop-shadow-blur;

        VerticalLayout {
            Rectangle {
                visible: show-search;
                height: show-search ? self.preferred-height : root.font-size / 3;
                border-width: root.font-size / 20;
                border-color: root.text-color;
                border-radius: root.font-size / 3;

                HorizontalLayout {
                    Rectangle { width: root.font-size / 3; }
                    search-box := LineEdit {
                        input-type: search;
                        font-size: root.font-size;
                        text-color: root.text-color;
                        enabled: show-search;
                    }
                    Rectangle { width: root.font-size / 3; }
                }
            }
            list := StandardListView {
                width: parent.width;
                height: expanded ? full-height - root.font-size * 1.5 : 0px;
                text-color: root.text-color;
                font-size: root.font-size;
                selected-color: root.background-color;
                selected-bg: self.text-color;
                background: background-color;
                model: entries;
                current-item: current;
                mouse-drag-pan-enabled: true;

                current-item-changed(current-item) => {
                    expanded = false;
                    picked(entries[current-item].text);
                }
            }
        }
    }
}
