import { StandardListView } from "listview.slint";

export component Picker inherits Rectangle {
    in-out property<bool> expanded: false;
    in property<int> current: 0;
    in property<color> text-color;
    in property<[StandardListViewItem]> entries;
    in property<length> full-height;
    in property<length> full-width;
    in property<length> font-size;
    in property<color> background-color;
    in property<length> picker-border-radius;
    in property<length> picker-drop-shadow-blur;
    in property<color> picker-drop-shadow-color;
    in property<length> picker-x;

    callback picked(string);

    public function update-current(current-item: int) {
        list.current-item = current-item;
    }

    Text {
        text: entries[list.current-item].text;
        color: text-color;
        font-size: parent.font-size;
        
        TouchArea {
            clicked => {
                expanded = true;
                list.bring-into-view(list.current-item);
            }
        }
    }
    Rectangle {
        z: 4;
        height: expanded ? full-height : 0px;
        width: expanded ? full-width : 0px;
        y: 0;
        x: picker-x;
        background: background-color;
        border-radius: root.picker-border-radius;
        drop-shadow-color: root.picker-drop-shadow-color;
        drop-shadow-blur: root.picker-drop-shadow-blur;

        list := StandardListView {
            width: parent.width;
            height: parent.height;
            text-color: root.text-color;
            font-size: root.font-size;
            selected-color: root.background-color;
            selected-bg: self.text-color;
            background: background-color;
            model: entries;
            current-item: current;
            mouse-drag-pan-enabled: true;

            current-item-changed(current-item) => {
                expanded = false;
                picked(entries[current-item].text);
            }
        }
    }
}
