import "./ubuntu-condensed.ttf";
import { Picker } from "picker.slint";
import { StandardListView } from "listview.slint";

global Palette {
    in property<color> bg: #002b36;
    in property<color> fg: #fdf6e3;
}
struct PrayerTime {
    prayer: string,
    time: string,
    ampm: string,
}
export component Clock inherits Window {
    in property<string> date;
    in property<string> time;
    in property<string> next-prayer;
    in-out property<string> current-prayer;
    in property<bool> adhan-playing: false;
    in-out property<[PrayerTime]> prayer-times;
    in property<length> calc-px: min(root.width / 1280, root.height / 600);
    in property<length> border-radius: 10 * calc-px;
    in property<int> city;
    in property<[StandardListViewItem]> cities;
    in property<int> country;
    in property<[StandardListViewItem]> countries;
    in property<string> school;

    callback city_picked <=> city_picker.picked;
    callback country_picked <=> country_picker.picked;
    callback school_picked <=> school_picker.picked;

    public function update-city(new-city: int) {
        city_picker.update-current(new-city);
    }
    public function update-prayer-times(new: [PrayerTime]) {
        prayer-times = new;
    }
    public function update-current-prayer(new: string) {
        current-prayer = new;
    }

    default-font-family: "Ubuntu Condensed";
    title: "Adhan Clock";
    icon: @image-url("../resources/drawable/icon.png");

    Image {
        source: @image-url("../bg.jpg");
        width: parent.width;
        height: parent.height;
        image-fit: cover;
    }
    Rectangle {
        width: root.width * 273% / 5;
        height: root.height * 245% / 4;
        x: root.width * 3%;
        y: root.height * 5%;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;

        VerticalLayout {
            Rectangle {vertical-stretch: 1;}
            Text {
                text: time;
                color: Palette.fg;
                font-size: calc-px * 144;
                horizontal-alignment: center;
                vertical-stretch: 0;
            }
            Text {
                text: date;
                color: Palette.fg;
                font-size: calc-px * 116;
                horizontal-alignment: center;
                vertical-stretch: 0;
            }
            Rectangle {vertical-stretch: 1;}
        }
    }
    Rectangle {
        width: root.width * 182% / 5;
        height: root.height * 245% / 4;
        x: root.width * 303% / 5;
        y: root.height * 5%;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;

        Text {
            text: adhan-playing ? current-prayer + "\ntime" : next-prayer;
            color: Palette.fg;
            font-size: calc-px * 107;
            horizontal-alignment: center;
        }
    }
    for time[i] in prayer-times: Rectangle {
        width: root.width * 79% / 6;
        height: root.height * 75% / 4;
        y: root.height * 315% / 4;
        x: root.width * 3% + i * root.width * 97% / 6;
        background: (time.prayer == current-prayer) ? Palette.fg : Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #0006;
        drop-shadow-blur: 2 * border-radius;

        VerticalLayout {
            Rectangle {vertical-stretch: 1;}
            HorizontalLayout {
                vertical-stretch: 0;

                Rectangle {horizontal-stretch: 1;}
                Text {
                    text: time.prayer;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 25;
                    horizontal-stretch: 0;
                }
                Rectangle {horizontal-stretch: 1;}
            }
            HorizontalLayout {
                vertical-stretch: 0;

                Rectangle {horizontal-stretch: 1;}
                Text {
                    text: time.time;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 64;
                    horizontal-stretch: 0;
                }
                Text {
                    text: time.ampm;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 25;
                    horizontal-stretch: 0;
                }
                Rectangle {horizontal-stretch: 1;}
            }
            Rectangle {vertical-stretch: 1;}
        }
    }
    TouchArea {
        clicked => {
            city-picker.expanded = false;
            country-picker.expanded = false;
            school-picker.expanded = false;
        }
    }
    Rectangle {
        width: root.width * 94%;
        height: root.height * 5%;
        x: root.width * 3%;
        y: root.height * 280% / 4;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;
        HorizontalLayout {
            out property<length> font-size: min(root.height * 3%, root.width * 3%);

            alignment: center;

            Text {
                text: "Displaying ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            school_picker := Picker {
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: school == "Majority time" ? 0 : 1;
                entries: [{text: "Majority time"}, {text: "Hanafi time"}];
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(country_picker.expanded || city_picker.expanded);
            }
            Text {
                text: " for ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            city_picker := Picker {
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: city;
                entries: cities;
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(country_picker.expanded || school_picker.expanded);
            }
            Text {
                z: 2;
                text: ", ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            country_picker := Picker {
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: country;
                entries: countries;
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(city_picker.expanded || school_picker.expanded);
            }
            Text {
                z: 2;
                text: ".";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
        }
    }
}
