// SPDX-License-Identifier: GPL-3.0-only

import "./ubuntu-condensed.ttf";
import { Picker } from "picker.slint";
import { StandardListView } from "listview.slint";

global Palette {
    in property<color> bg: #002b36;
    in property<color> fg: #fdf6e3;
}
struct PrayerTime {
    prayer: string,
    time: string,
    ampm: string,
}
export component Clock inherits Window {
    in property<string> date;
    in property<string> time;
    in property<string> next-prayer;
    in-out property<string> current-prayer;
    in property<string> school;

    in property<bool> adhan-playing: false;

    in-out property<[PrayerTime]> prayer-times;

    in property<length> calc-px: min(col-width / 41, row-height / 30);
    in property<length> border-radius: 10 * calc-px;
    in property<length> col-width: self.width / 31;
    in property<length> row-height: self.height / 20;

    in property<int> city;
    in property<[StandardListViewItem]> cities;
    in property<int> country;
    in property<[StandardListViewItem]> countries;

    callback city_picked <=> city_picker.picked;
    callback country_picked <=> country_picker.picked;
    callback school_picked <=> school_picker.picked;

    callback search-country <=> country_picker.searched;
    callback search-city <=> city_picker.searched;

    public function show-country(item: int) {
        country_picker.bring-into-view(item);
    }
    public function show-city(item: int) {
        city_picker.bring-into-view(item);
    }

    public function update-city(new-city: int) {
        city_picker.update-current(new-city);
    }
    public function update-prayer-times(new: [PrayerTime]) {
        prayer-times = new;
    }
    public function update-current-prayer(new: string) {
        current-prayer = new;
    }

    default-font-family: "Ubuntu Condensed";
    title: "Adhan Clock";
    icon: @image-url("../resources/drawable/icon.png");

    Image {
        source: @image-url("../bg.jpg");
        width: root.width;
        height: root.height;
        image-fit: cover;
    }
    Rectangle {
        width: col-width * 17;
        height: row-height * 11;
        x: col-width;
        y: row-height;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;

        VerticalLayout {
            Rectangle {vertical-stretch: 1;}
            Text {
                text: time;
                color: Palette.fg;
                font-size: calc-px * 144;
                horizontal-alignment: center;
                vertical-stretch: 0;
            }
            Text {
                text: date;
                color: Palette.fg;
                font-size: calc-px * 116;
                horizontal-alignment: center;
                vertical-stretch: 0;
            }
            Rectangle {vertical-stretch: 1;}
        }
    }
    Rectangle {
        width: col-width * 11;
        height: row-height * 11;
        x: col-width * 19;
        y: row-height;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;

        Text {
            text: adhan-playing ? current-prayer + "\ntime" : next-prayer;
            color: Palette.fg;
            font-size: calc-px * 107;
            horizontal-alignment: center;
        }
    }
    for time[i] in prayer-times: Rectangle {
        width: col-width * 4;
        height: row-height * 4;
        y: row-height * 15;
        x: col-width + i * col-width * 5;
        background: (time.prayer == current-prayer) ? Palette.fg : Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #0006;
        drop-shadow-blur: 2 * border-radius;

        VerticalLayout {
            Rectangle {vertical-stretch: 1;}
            HorizontalLayout {
                vertical-stretch: 0;

                Rectangle {horizontal-stretch: 1;}
                Text {
                    text: time.prayer;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 25;
                    horizontal-stretch: 0;
                }
                Rectangle {horizontal-stretch: 1;}
            }
            HorizontalLayout {
                vertical-stretch: 0;

                Rectangle {horizontal-stretch: 1;}
                Text {
                    text: time.time;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 64;
                    horizontal-stretch: 0;
                }
                Text {
                    text: time.ampm;
                    color: (time.prayer == current-prayer) ? Palette.bg : Palette.fg;
                    font-size: calc-px * 25;
                    horizontal-stretch: 0;
                }
                Rectangle {horizontal-stretch: 1;}
            }
            Rectangle {vertical-stretch: 1;}
        }
    }
    TouchArea {
        clicked => {
            city-picker.expanded = false;
            country-picker.expanded = false;
            school-picker.expanded = false;
        }
    }
    Rectangle {
        width: col-width * 29;
        height: row-height;
        x: col-width;
        y: row-height * 13;
        background: Palette.bg;
        border-radius: border-radius;
        drop-shadow-color: #000;
        drop-shadow-blur: 2 * border-radius;
        HorizontalLayout {
            out property<length> font-size: min(row-height / 1.5, col-width / 1.05);

            alignment: center;

            Text {
                text: "Displaying ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            school_picker := Picker {
                y: self.expanded ? 0 - root.virtual-keyboard-size.height : 0px;
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: school == "Majority time" ? 0 : 1;
                entries: [{text: "Majority time"}, {text: "Hanafi time"}];
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(country_picker.expanded || city_picker.expanded);
                show-search: false;
            }
            Text {
                text: " for ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            city_picker := Picker {
                y: self.expanded ? 0 - root.virtual-keyboard-size.height : 0px;
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: city;
                entries: cities;
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(country_picker.expanded || school_picker.expanded);
                suffix: ",";
            }
            Text {
                z: 2;
                text: " ";
                color: Palette.fg;
                font-size: parent.font-size;
                vertical-alignment: center;
            }
            country_picker := Picker {
                y: self.expanded ? 0 - root.virtual-keyboard-size.height : 0px;
                z: 3;
                full-height: root.height * 115% / 4;
                full-width: root.width * 60%;
                picker-x: 0 - self.x + root.width * 17%;
                text-color: Palette.fg;
                font-size: parent.font-size;
                background-color: Palette.bg;
                current: country;
                entries: countries;
                picker-border-radius: border-radius;
                picker-drop-shadow-color: #000;
                picker-drop-shadow-blur: 2 * border-radius;
                visible: !(city_picker.expanded || school_picker.expanded);
                suffix: ".";
            }
        }
    }
}
