// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export struct TextStyle {
    font-size: relative-font-size,
    font-weight: int,
}

export global CosmicFontSettings {
    out property <TextStyle> body-strong: { font-size: 14pt * 1rem / 14pt, font-weight: FontWeight.semi-bold };
    out property <TextStyle> title: { font-size: 24pt * 1rem / 14pt, font-weight: FontWeight.light };
}

export global Icons {
    out property <image> arrow-down: @image-url("_arrow_down.svg");
    out property <image> arrow-up: @image-url("_arrow_up.svg");
    out property <image> check-mark: @image-url("_check-mark.svg");
    out property <image> dropdown: @image-url("_pane_down.svg");
    out property <image> keyboard: @image-url("_keyboard.svg");
    out property <image> clock: @image-url("_clock.svg");
    out property <image> arrow-back: @image-url("_arrow_back.svg");
    out property <image> arrow-forward: @image-url("_arrow_forward.svg");
    out property <image> edit: @image-url("_edit.svg");
    out property <image> calendar: @image-url("_calendar.svg");
}

export global CosmicSizeSettings {
    out property <length> item-height: 40px;
}
